# -*- coding: utf-8 -*-
"""Day 3 activity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDAJiPfgYdkIf8ZjGY2nLe9jRRCWkPyl

NumPy(Numerical python)
"""

import numpy as np
a=np.array([10,23,24,95])
b=np.array([45,89,56,73])
c=np.array([52,95,34,49])
d=a+b
e=d-c
print("Addition:",d)
print("subtraction:",e)
print("multiplication:",a*c)
print("division:",a/b)