# -*- coding: utf-8 -*-
"""nms internship 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCaXWP5RmC4tOvskY3w4W_RASsUoIHMS
"""

name="Nagajothi"
age=20
CGPA=8.5
placed=True
print("Student Name:",name)
print("Age:",age)
print("CGPA:",CGPA)
print("placed:",placed)
print(type(name))
print(type(age))
print(type(CGPA))
print(type(placed))